In [1]:
import pandas as pd

# pandas的描述性统计

# 4.3 统计计算

In [2]:
df = pd.read_excel('team.xlsx',index_col='name')
df.head()

team    Q1  Q2    Q3  Q4
name                          
Liver    E  89.0  21  24.0   1
Arry     C   NaN  37  37.0   2
Ack      A  57.0  60   NaN   3
Eorge    C  93.0   4  71.0   4
Oah      D  93.0  49   NaN   5

# 4.3.1 描述统计

In [3]:
# 1，描述统计（对所有数字列的统计表）
# 总数、平均数、方差、最小值、四分位数、最大值。
df.describe()

Q1          Q2         Q3          Q4
count  99.000000  100.000000  98.000000  100.000000
mean   49.686869   51.630000  52.938776   50.500000
std    30.274474   29.910187  26.569037   29.011492
min     1.000000    1.000000   1.000000    1.000000
25%    19.000000   25.750000  30.000000   25.750000
50%    52.000000   48.500000  55.000000   50.500000
75%    76.000000   77.000000  76.750000   75.250000
max    98.000000   99.000000  99.000000  100.000000

In [4]:
# 2，描述统计（对非数字列的统计）
# 数量、不重复值的数量、最大值（按首字母顺序）、重复字符最多的数量
pd.Series(['a','b','c','c','b','c','c','a']).describe()

count     8
unique    3
top       c
freq      4
dtype: object

In [5]:
pd.Series(['a','b','c','c','b','c','c','a']).describe().unique()

array([8, 3, 'c', 4], dtype=object)

In [6]:
pd.Series(['a','b','c','c','b','c','c','a']).describe().unique()[2]

'c'

In [7]:
# 3,时间数据的描述
pd.Series(pd.date_range('2000-01-01','2000-05-01')).describe()

/var/folders/f7/4z7jtb213fs0mtgbw_0vs2600000gn/T/ipykernel_7522/1209817977.py:2: FutureWarning: Treating datetime data as categorical rather than numeric in `.describe` is deprecated and will be removed in a future version of pandas. Specify `datetime_is_numeric=True` to silence this warning and adopt the future behavior now.
  pd.Series(pd.date_range('2000-01-01','2000-05-01')).describe()


count                     122
unique                    122
top       2000-01-01 00:00:00
freq                        1
first     2000-01-01 00:00:00
last      2000-05-01 00:00:00
dtype: object

In [8]:
# 4,重新设置四分位数
df.describe(percentiles=[.05,.25,.75,.95])

Q1          Q2         Q3          Q4
count  99.000000  100.000000  98.000000  100.000000
mean   49.686869   51.630000  52.938776   50.500000
std    30.274474   29.910187  26.569037   29.011492
min     1.000000    1.000000   1.000000    1.000000
5%      4.900000    6.850000  12.850000    5.950000
25%    19.000000   25.750000  30.000000   25.750000
50%    52.000000   48.500000  55.000000   50.500000
75%    76.000000   77.000000  76.750000   75.250000
95%    93.000000   95.050000  91.300000   95.050000
max    98.000000   99.000000  99.000000  100.000000

In [9]:
import numpy as np

# 报错
# df.describe(include=[np.object,np.number]) 指定类型
# df.describe(exclude=[np.object]) 排除类型

# 4.3.2 数学统计

In [10]:
# 1，对单个数字列的描述计算
df.Q1.mean()

49.686868686868685

In [11]:
# 报错，因为统计的列中有非数字列，如 name和team，所以必须先对name和team索引
# df.Q1.mean(axis='columns')
# df.mean(1)

In [13]:
# 统计前五行Q1-Q4平均值
df2 = pd.read_excel('team.xlsx')
df2.set_index(['team','name']).mean(1).head()
df2.set_index(['team','name']).mean(axis='columns').head() #同上
df2.set_index(['team','name']).mean(axis=1).head() #同上

team  name 
E     Liver    33.750000
C     Arry     25.333333
A     Ack      40.000000
C     Eorge    43.000000
D     Oah      49.000000
dtype: float64

# 4.3.3 统计函数

In [14]:
df3 = pd.read_excel('team.xlsx', index_col=[0,1])

In [15]:
# 1,返回所有行的均值
df3.mean(1).head()

name   team
Liver  E       33.750000
Arry   C       25.333333
Ack    A       40.000000
Eorge  C       43.000000
Oah    D       49.000000
dtype: float64

In [16]:
# 2，返回所有列的均值
df3.mean(0).head()

Q1    49.686869
Q2    51.630000
Q3    52.938776
Q4    50.500000
dtype: float64

In [17]:
# 3, 返回列与列之间的相关系数
df3.corr()

Q1        Q2        Q3        Q4
Q1  1.000000  0.089783 -0.127946 -0.235339
Q2  0.089783  1.000000  0.039059  0.089871
Q3 -0.127946  0.039059  1.000000 -0.018234
Q4 -0.235339  0.089871 -0.018234  1.000000

In [19]:
# 统计每列的数量
df3.count()

Q1     99
Q2    100
Q3     98
Q4    100
dtype: int64

In [20]:
df3.count().Q1

99

In [22]:
# 统计每列最大值
df3.max()

Q1     98.0
Q2     99.0
Q3     99.0
Q4    100.0
dtype: float64

In [23]:
df3.min()

Q1    1.0
Q2    1.0
Q3    1.0
Q4    1.0
dtype: float64

In [24]:
# 绝对值
df3.abs().head()

Q1  Q2    Q3  Q4
name  team                    
Liver E     89.0  21  24.0   1
Arry  C      NaN  37  37.0   2
Ack   A     57.0  60   NaN   3
Eorge C     93.0   4  71.0   4
Oah   D     93.0  49   NaN   5

In [21]:
df3.median()

Q1    52.0
Q2    48.5
Q3    55.0
Q4    50.5
dtype: float64

In [22]:
df3.std()

Q1    30.274474
Q2    29.910187
Q3    26.569037
Q4    29.011492
dtype: float64

In [23]:
df3.var()

Q1    916.543805
Q2    894.619293
Q3    705.913739
Q4    841.666667
dtype: float64

In [24]:
df3.sem()

Q1    3.042699
Q2    2.991019
Q3    2.683878
Q4    2.901149
dtype: float64

In [25]:
df3.mode().head()

Q1    Q2    Q3  Q4
0   9.0  34.0  87.0   1
1  15.0  38.0   NaN   2
2   NaN   NaN   NaN   3
3   NaN   NaN   NaN   4
4   NaN   NaN   NaN   5

In [26]:
df3.mode().Q1[1]

15.0

In [27]:
df3.prod()

Q1    3.482066e+153
Q2     0.000000e+00
Q3    2.894091e+160
Q4     0.000000e+00
dtype: float64

In [28]:
df3.cumprod().head()

Q1       Q2       Q3   Q4
name  team                                   
Liver E           89.0       21     24.0    1
Arry  C            NaN      777    888.0    2
Ack   A         5073.0    46620      NaN    6
Eorge C       471789.0   186480  63048.0   24
Oah   D     43876377.0  9137520      NaN  120

In [29]:
df3.cumsum(axis=0).head()

Q1   Q2     Q3  Q4
name  team                       
Liver E      89.0   21   24.0   1
Arry  C       NaN   58   61.0   3
Ack   A     146.0  118    NaN   6
Eorge C     239.0  122  132.0  10
Oah   D     332.0  171    NaN  15

In [30]:
df3.nunique()

Q1     65
Q2     62
Q3     64
Q4    100
dtype: int64

In [31]:
df3.idxmax()

Q1    (Lincoln4, C)
Q2      (Harley, B)
Q3        (Lfie, A)
Q4         (Ben, E)
dtype: object

In [32]:
df3.idxmin()

Q1    (Sebastian, C)
Q2        (Roman, E)
Q3     (Lincoln4, C)
Q4        (Liver, E)
dtype: object

In [33]:
df3.cummax().head()

Q1  Q2    Q3  Q4
name  team                    
Liver E     89.0  21  24.0   1
Arry  C      NaN  37  37.0   2
Ack   A     89.0  60   NaN   3
Eorge C     93.0  60  71.0   4
Oah   D     93.0  60   NaN   5

In [34]:
df3.cummin().head()

Q1  Q2    Q3  Q4
name  team                    
Liver E     89.0  21  24.0   1
Arry  C      NaN  21  24.0   1
Ack   A     57.0  21   NaN   1
Eorge C     57.0   4  24.0   1
Oah   D     57.0   4   NaN   1

In [35]:
df3.skew()

Q1   -0.077595
Q2   -0.013285
Q3   -0.074795
Q4    0.000000
dtype: float64

In [36]:
df3.kurt()

Q1   -1.364042
Q2   -1.336805
Q3   -1.140104
Q4   -1.200000
dtype: float64

In [37]:
df3.quantile()

Q1    52.0
Q2    48.5
Q3    55.0
Q4    50.5
Name: 0.5, dtype: float64

In [38]:
df3.sum(1).head()

name   team
Liver  E       135.0
Arry   C        76.0
Ack    A       120.0
Eorge  C       172.0
Oah    D       147.0
dtype: float64

In [39]:
df3.sum(1, skipna=False).head()

name   team
Liver  E       135.0
Arry   C         NaN
Ack    A         NaN
Eorge  C       172.0
Oah    D         NaN
dtype: float64

In [40]:
# df3.sum(level=1)
df3.sum(1).Liver.E

135.0

In [41]:
df3.sum(1,min_count=1)

name      team
Liver     E       135.0
Arry      C        76.0
Ack       A       120.0
Eorge     C       172.0
Oah       D       147.0
                  ...  
Gabriel   C       290.0
Austin7   C       179.0
Lincoln4  C       290.0
Eli       E       242.0
Ben       E       205.0
Length: 100, dtype: float64

# 4.3.4 非统计计算

In [88]:
# any()一个序列中满足一个True，则返回True；
# DataFrame.any(self, axis=0, bool_only=None, skipna=True, level=None, **kwargs)
# bool_only:用于是否只利用序列中的Boolean值进行判断
# skipna，是否跳过NA/null值，False表示跳过，True表示不跳过
pd.Series([False,False]).any()

False

In [43]:
pd.Series([True,False]).any()

True

In [44]:
pd.Series([]).any()

False

In [45]:
pd.Series([np.nan]).any()

False

In [46]:
# skipna=False ，如有有nan（缺失值）则不计算结果，即忽略。
# 因此这里指忽略np.nan
pd.Series([np.nan]).any(skipna=False)

True

In [47]:
# 反之，skipna=True，有nan时则计算结果，不忽略nan
pd.Series([np.nan]).any(skipna=True)

False

In [48]:
# nan(NAN，Nan):not a number 表示不是一个数字
# np.nan是一个float类型的数据, 因为nan不是一个数，所以相关计算都无法得到数字。
a = np.nan
type(a)

float

In [49]:
# 所有涉及nan的操作，返回的都是nan
np.nan + 1

nan

In [50]:
np.nan != np.nan

True

In [51]:
# 何时会出现nan？
# 当我们读取本地文件为float时，如果有缺失或者做了不合适的计算，比如无穷大(inf)减去无穷大，一个数除以0等，就会显示 nan

In [52]:
# all()一个序列中所有值为True时，返回True，否则为False。

pd.Series([True,True]).all()

True

In [53]:
pd.Series([True,False]).all()

False

In [54]:
pd.Series([]).all()

True

In [55]:
pd.Series([np.nan]).all()

True

In [56]:
pd.Series([np.nan]).all(skipna=False)

True

In [57]:
df = pd.DataFrame({'col1':[True,True], 'col2':[True,False], 'col3':[False,False]})
df

col1   col2   col3
0  True   True  False
1  True  False  False

In [58]:
# 列项统计
df.all(axis =0)

col1     True
col2    False
col3    False
dtype: bool

In [59]:
# 横项统计
df.all(1)

0    False
1    False
dtype: bool

In [60]:
df.all(axis=None)

False

In [61]:
# 空值的显示True
df3.isnull().head()

Q1     Q2     Q3     Q4
name  team                            
Liver E     False  False  False  False
Arry  C      True  False  False  False
Ack   A     False  False   True  False
Eorge C     False  False  False  False
Oah   D     False  False   True  False

In [62]:
# 显示所有列中哪个列有空值，有空值的显示True
# Q1和Q3列有空值
df3.isnull().any(axis=0)

Q1     True
Q2    False
Q3     True
Q4    False
dtype: bool

In [63]:
# 含有空值的列数
# 2列，分别是Q1和Q3
df3.isnull().any(axis=0).sum()

2

In [64]:
# 查看各行是否有空值，有空值显示True
# Arry,Ack,Oah有空值
df3.isnull().any(axis=1).head()

name   team
Liver  E       False
Arry   C        True
Ack    A        True
Eorge  C       False
Oah    D        True
dtype: bool

In [65]:
# 含有空值的行数
df.isnull().any(axis=1).sum()

0

In [66]:
df3

Q1  Q2    Q3   Q4
name     team                     
Liver    E     89.0  21  24.0    1
Arry     C      NaN  37  37.0    2
Ack      A     57.0  60   NaN    3
Eorge    C     93.0   4  71.0    4
Oah      D     93.0  49   NaN    5
...             ...  ..   ...  ...
Gabriel  C     48.0  59  87.0   96
Austin7  C     21.0  31  30.0   97
Lincoln4 C     98.0  93   1.0   98
Eli      E     11.0  74  58.0   99
Ben      E     21.0  43  41.0  100

[100 rows x 4 columns]

In [67]:
import numpy as np
df3.replace(np.nan, 100,inplace=True)

In [68]:
df3.head()

Q1  Q2     Q3  Q4
name  team                      
Liver E      89.0  21   24.0   1
Arry  C     100.0  37   37.0   2
Ack   A      57.0  60  100.0   3
Eorge C      93.0   4   71.0   4
Oah   D      93.0  49  100.0   5

In [69]:
# 四舍五入
df.round(2).head()

col1   col2   col3
0  True   True  False
1  True  False  False

In [86]:
df3['排名']=df3['Q1'].rank(method='dense').astype("int")

In [71]:
df3

Q1  Q2     Q3   Q4  排名
name     team                           
Liver    E      89.0  21   24.0    1  58
Arry     C     100.0  37   37.0    2  66
Ack      A      57.0  60  100.0    3  34
Eorge    C      93.0   4   71.0    4  62
Oah      D      93.0  49  100.0    5  62
...              ...  ..    ...  ...  ..
Gabriel  C      48.0  59   87.0   96  29
Austin7  C      21.0  31   30.0   97  18
Lincoln4 C      98.0  93    1.0   98  65
Eli      E      11.0  74   58.0   99   9
Ben      E      21.0  43   41.0  100  18

[100 rows x 5 columns]

In [72]:
df3['Q1'] = df3['Q1'].clip(0,50)

In [73]:
df3.head()

Q1  Q2     Q3  Q4  排名
name  team                         
Liver E     50.0  21   24.0   1  58
Arry  C     50.0  37   37.0   2  66
Ack   A     50.0  60  100.0   3  34
Eorge C     50.0   4   71.0   4  62
Oah   D     50.0  49  100.0   5  62

In [74]:
# Q1保留2位，Q2保留1位，没看到效果
df.round({'Q1':2,'Q2':1}).head()

col1   col2   col3
0  True   True  False
1  True  False  False

In [85]:
df = pd.read_excel('team.xlsx',index_col='name')
# 统计每列不同值得个数
df.nunique()

team      5
Q1       65
Q2       62
Q3       64
Q4      100
dtype: int64

In [76]:
# unique()方法返回的是去重之后的不同值
s = pd.Series([1,3,3,4,2,1])
s.unique()

array([1, 3, 4, 2])

In [77]:
# nunique()方法返回不同值的个数
s.nunique()

4

In [83]:
# 如果Series中有None时，
s = pd.Series([1,3,3,None,4,2,1])
s.unique()

array([ 1.,  3., nan,  4.,  2.])

In [84]:
# 如果Series中有None时，排除None
s.nunique()

4

In [80]:
# 如果Series中有None时，包含None
s.nunique(dropna=False)

5

In [81]:
# 判断值是否是nan ， 是None返回True，其他返回False
s.isna()

0    False
1    False
2    False
3     True
4    False
5    False
6    False
dtype: bool

In [82]:
# 判断值是否是nan ， 是None返回False，其他返回True
s.notna()

0     True
1     True
2     True
3    False
4     True
5     True
6     True
dtype: bool