In [21]:
import numpy as np
x = np.arange(6).reshape(2,3)
y = np.arange(6).reshape(2,3)

In [8]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [9]:
a.ndim

2

In [19]:
b = np.arange(6).reshape(2,3)

In [20]:
b

array([[0, 1, 2],
       [3, 4, 5]])

In [26]:
def add(x,y):
#     assert len(x.shape) == 2 
#     assert x.shape == y.shape
    x = x.copy() 
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
             x[i, j] += y[i, j]
    return x
    

In [27]:
add(3,4)

AttributeError: 'int' object has no attribute 'copy'

In [28]:
z= x+y

In [29]:
z = np.maximum(z,0)

In [30]:
z

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [40]:
x = np.random.random((64, 3, 132, 10)) 
y = np.random.random((10)) 
z = np.maximum(x, y)

In [41]:
z

array([[[[0.82072125, 0.91962279, 0.32546571, ..., 0.31654533,
          0.6657584 , 0.7726001 ],
         [0.75706005, 0.91962279, 0.59280685, ..., 0.1622871 ,
          0.58230893, 0.7726001 ],
         [0.75706005, 0.91962279, 0.63714721, ..., 0.46096418,
          0.58230893, 0.88329855],
         ...,
         [0.75706005, 0.91962279, 0.32546571, ..., 0.8972192 ,
          0.58230893, 0.7726001 ],
         [0.75706005, 0.95496875, 0.32546571, ..., 0.36563077,
          0.58230893, 0.7726001 ],
         [0.75706005, 0.91962279, 0.32546571, ..., 0.11432296,
          0.58230893, 0.7726001 ]],

        [[0.75706005, 0.91962279, 0.49485683, ..., 0.17299367,
          0.75947407, 0.7726001 ],
         [0.98486455, 0.91962279, 0.87098879, ..., 0.84531715,
          0.58230893, 0.7726001 ],
         [0.75706005, 0.91962279, 0.60112781, ..., 0.66091278,
          0.58230893, 0.7726001 ],
         ...,
         [0.75706005, 0.91962279, 0.96163942, ..., 0.29918618,
          0.58230893, 0.7

In [42]:
z.shape

(64, 3, 132, 10)

In [43]:
A=[1,2,3,4,5]
B=[5,4,3,2,1]

In [44]:
np.dot(A,B)

35

In [45]:
A = np.array( [[1,2],
               [3,4]] )
B = np.array( [[5,6],
               [7,8]] )

In [47]:
A.dot(B)

array([[19, 22],
       [43, 50]])

In [48]:
A=np.array([1,2,3,4]).reshape(4,1)
B=np.array([1,2,3,4,5,6,7,8]).reshape(2,4)

In [49]:
A.shape

(4, 1)

In [50]:
B.shape

(2, 4)

In [51]:
np.dot(A,B)

ValueError: shapes (4,1) and (2,4) not aligned: 1 (dim 1) != 2 (dim 0)

In [52]:
np.dot(B,A)

array([[30],
       [70]])

In [53]:
B.dot(A)

array([[30],
       [70]])