In [1]:
import numpy as np

In [2]:
n = np.array([[5, 10, 15],
              [20, 125, 30],
              [35, 40, 45]])

In [3]:
n.min()

5

In [4]:
n.max()

125

In [5]:
# 某一行中最大值组成数组
n.max(axis=0)

array([ 35, 125,  45])

In [6]:
# 某一列中最大值组成数组
n.max(1)

array([ 15, 125,  45])

In [7]:
n.mean().round(2)

36.11

In [8]:
# 列求和组成数组  
n.sum(axis=0)

array([ 60, 175,  90])

In [9]:
# 行求和组成数组
n.sum(1)

array([ 30, 175, 120])

In [10]:
n.sum()

325

In [11]:
# 列求平均值组成数组
n.mean(0)

array([20.        , 58.33333333, 30.        ])

In [12]:
# 行求平均值组成数组
n.mean(1)

array([10.        , 58.33333333, 40.        ])

In [13]:
n1 = np.arange(5)

In [14]:
n1

array([0, 1, 2, 3, 4])

In [15]:
# np. exp(x)   e的x幂次方
np.exp(n1)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [16]:
# 开根号
np.sqrt(n1)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [17]:
# np.floor() 向下取整
a = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])

In [18]:
np.floor(a)

array([-2., -2., -1.,  0.,  1.,  1.,  2.])

In [19]:
# 排序
a = np.array([[4, 3, 5], [1, 6, 1]])
a

array([[4, 3, 5],
       [1, 6, 1]])

In [20]:
# 行排序
np.sort(a)  # 等同于 np.sort(a,1)   或 np.sort(a,axis=1)

array([[3, 4, 5],
       [1, 1, 6]])

In [21]:
# 列排序
np.sort(a)

array([[3, 4, 5],
       [1, 1, 6]])

In [22]:
# np.argsort() 返回元素位置的排序索引
x = np.array([44, 23, 10, 24])
arg = np.argsort(x)
arg

array([2, 1, 3, 0], dtype=int64)

In [23]:
x[arg]

array([10, 23, 24, 44])

In [24]:
np.argsort(arg)  # 对 array([2, 1, 3, 0], dtype=int64) 进行再索引排序

array([3, 1, 0, 2], dtype=int64)

In [25]:
# 返回数组[44, 23, 10, 24]中最大值的索引号
arg[-1]

0

In [26]:
# 返回数组中最小值的索引号
arg[0]

2

In [27]:
# 返回数组中最大元素的索引
a = np.array([44, 23, 3310, 124])
a.argmax()

2

In [28]:
a.argmin()

1

In [29]:
n1 = np.array([[11, 1],
               [0, 5]])
n2 = np.array([[2, 0],
               [3, 4]])

In [30]:
n1

array([[11,  1],
       [ 0,  5]])

In [31]:
n2

array([[2, 0],
       [3, 4]])

In [32]:
# [11*2,1*0],[0*3,5*4]
n1*n2

array([[22,  0],
       [ 0, 20]])

In [33]:
np.multiply(n1,n2)

array([[22,  0],
       [ 0, 20]])

In [34]:
np.multiply(2, 3)

6

In [35]:
np.multiply(n1, 3)

array([[33,  3],
       [ 0, 15]])

In [36]:
A = np.array( [[1,2],
               [3,4]] )
B = np.array( [[5,6],
               [7,8]] )

In [37]:
A.dot(B)

array([[19, 22],
       [43, 50]])

In [38]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [39]:
a= np.ones((3,7))

In [40]:
a

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [41]:
b= np.ones((7,3))*4

In [42]:
b

array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

In [43]:
a.dot(b)

array([[28., 28., 28.],
       [28., 28., 28.],
       [28., 28., 28.]])

In [44]:
A=[1,2,3,4,5]
B=[5,4,3,2,1]

In [45]:
np.dot(A,B)

35

In [46]:
A=np.array([1,2,3,4]).reshape(4,1)
B=np.array([1,2,3,4,5,6,7,8]).reshape(2,4)

In [47]:
A

array([[1],
       [2],
       [3],
       [4]])

In [48]:
B

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [49]:
# 报错了，A·B中, 因为A的x方向为1个元素，而B的y方向为2个元素。无法进行点积运算。
np.dot(A,B)

ValueError: shapes (4,1) and (2,4) not aligned: 1 (dim 1) != 2 (dim 0)

In [ ]:
# B·A中，B的x方向有4个元素，A的y方向有四个元素。
# 最终的结果，C在y方向上跟随B，有两个元素；在x方向上跟随A，有一个元素。C：(2,1)。
np.dot(B,A)

In [ ]:
A1=np.array([1,2]).reshape(2,1)
W=np.array([1,2,3,4,5,6]).reshape(3,2)
print('A2=W·A1:\n',np.dot(W,A1))

In [ ]:
A1


In [ ]:
W

In [ ]:
np.matmul(W,A1)

In [ ]:
n1 = np.array([[10, 11],
               [12, 13]])
n2 = np.array([[40, 51],
               [62, 73]])

In [ ]:
# 横拼接
np.hstack((n1,n2))

In [ ]:
# 竖拼接
np.vstack((n1,n2))

In [ ]:
n3 = np.floor(10 * np.random.random((2, 12)))
n3

In [ ]:
np.hsplit(n3,3)

In [ ]:
np.hsplit(n3,(3,5))

In [ ]:
n3.T

In [ ]:
np.vsplit(n3.T,3)

In [ ]:
harr = np.floor(10 * np.random.random((2, 6)))
harr


In [ ]:
np.hsplit(harr, 3)

In [ ]:
np.hsplit(harr, (2, 4, 5))

In [ ]:
x = np.arange(16.0).reshape(2, 8)

In [ ]:
x

In [ ]:
np.hsplit(x, [1,2,6])

In [ ]:
n = np.array([-0.746, 4.6, 9.4, 7.447, 10.455, 121.555])


In [ ]:
np.around(n, decimals=-1)


In [ ]:
n = np.array([-1.7, -2.5, -0.2, 0.6, 1.2, 2.7, 11])


In [ ]:
np.ceil(n)

In [ ]:
data = np.random.random([2, 3])
data

In [ ]:
np.where(data>0.5,data,0)

In [ ]:
np.array([[i, i * i] for i in [5, 6, 7]])


In [ ]:
np.arange(9.).reshape(3, 3)

In [ ]:
np.arange(2, 10, 2)


In [ ]:
np.arange(start=2, stop=10, step=2)


In [ ]:
np.empty(shape=3)

In [ ]:
np.empty(shape=(2,3))

In [ ]:
np.empty(shape=(2,3),dtype=int)

In [ ]:
np.ones(5)

In [ ]:
np.ones(5).dtype

In [ ]:
np.full((2, 3), 7)

In [ ]:
n1=np.arange(0,40,10)

In [ ]:
np.tile(n1,(3,5))

In [ ]:
np.r_[[1,2,3],[4,5,6],[7,8,9]]


In [ ]:
a = np.array([[1, 2, 3],[7,8,9]])
b=np.array([[4,5,6],[1,2,3]])

In [ ]:
np.r_[a,b]


In [ ]:
 np.linspace(-5, 5, 5)

In [ ]:
 np.linspace(-5, 5, 5, False)

In [ ]:
 np.linspace(-5, 5, 5, False,True)

In [ ]:
 np.linspace(-5, 5, 5, False,True,int)

In [ ]:
b = np.array([[[1,2.0],[1,2],[5,6]]])

In [ ]:
b.ndim

In [ ]:
b.shape


In [ ]:
b.dtype

In [ ]:
a = np.array([5, 10, 15])


In [ ]:
a[1]

In [ ]:
a[0:2]

In [ ]:
a[:2]

In [ ]:
a[2:]

In [ ]:
b = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])


In [ ]:
b[1,2]

In [ ]:
b[:,1]

In [ ]:
b[:,0:2]

In [ ]:
b[1:3,0:2]

In [ ]:
n = np.array([[1, 2, 3, 4, 5], [2, 3, 4, 5, 6], [1, 3, 5, 7, 9]])

In [ ]:
b = n[:, 4] > 6


In [ ]:
b

In [ ]:
n[b] = 11

In [ ]:
n

In [ ]:
n[n>2]=11

In [ ]:
n

In [ ]:
n.ravel()

In [ ]:
n.resize(3,5)

In [ ]:
n

In [ ]:
n.reshape(3,5)

In [ ]:
n1 = np.array([1, 2, 3, 4, 5, 6, 7, 8])


In [ ]:
n1.shape

In [ ]:
b = np.array([[[1,2.0],[1,2],[5,6]]])

In [ ]:
b.shape

In [ ]:
n1 = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
n1

In [ ]:
n2 = n1.reshape(2, 4)

In [ ]:
n2

In [ ]:
n1

In [ ]:
n2.shape = (8)

In [ ]:
n2

In [ ]:
n3 = n1.reshape(2, 2, -1) 

In [ ]:
n3

In [ ]:
n3.shape

In [ ]:
n4 = n3.ravel()

In [ ]:
n4

In [ ]:
n5 = n3.resize(2,4)

In [ ]:
n3

In [ ]:
n5

In [ ]:
n3.T

In [ ]:
n = np.array(['1', '2', '0', '4'])

In [ ]:
n.dtype

In [ ]:
n2 = n.astype(float)

In [ ]:
n2.dtype

In [ ]:
n3 = n.astype(bool)

In [ ]:
n3.dtype

In [ ]:
arr = np.arange(6).reshape(2,3)
print('原数组：')
print(arr)
print('查看原数组的ID:')
print(id(arr))
print('创建arr的视图brr，brr = arr.view()')
brr = arr.view()
print('brr的id与arr的不相同:')
print(brr)
print(id(brr))
print('修改brr的形状arr的不会改变，但是更改brr里面的值arr的也会改变：')
brr.shape = (3,2)
brr[0,0] = 10
print('brr:')
print(brr)
print('arr:')
print(arr)
print()


In [ ]:
arr = np.arange(12)

In [ ]:
arr

In [ ]:
a=arr[3:]

In [ ]:
a

In [ ]:
b=arr[3:]

In [ ]:
b

In [ ]:
a[1]=123

In [ ]:
a

In [ ]:
b[2]=555

In [ ]:
b

In [ ]:
arr

In [ ]:
id(a)

In [ ]:
id(b)

In [ ]:
id(arr)

In [ ]:
n2 = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [ ]:
n2

In [ ]:
n_bool = (n2 == 10) | (n2 == 25) | (n2 == 45)

In [ ]:
n_bool

In [ ]:
n2[n_bool]

In [51]:
np.array([[1,2,3]])

array([[1, 2, 3]])

In [65]:
x = np.array([(1,2),(3,4),(5,6)],dtype=[('a','<i4'),('b','f4')])

In [66]:
x['a']

array([1, 3, 5])

In [71]:
x["b"]

array([2., 4., 6.], dtype=float32)

In [68]:
x

array([(1, 2.), (3, 4.), (5, 6.)], dtype=[('a', '<i4'), ('b', '<f4')])

In [69]:
x[0]

(1, 2.)

In [72]:
x = np.array([[1, 2], [3, 4]])

In [73]:
m = np.asmatrix(x)

In [74]:
m

matrix([[1, 2],
        [3, 4]])

In [75]:
x[0,0] = 5

In [76]:
m

matrix([[5, 2],
        [3, 4]])

In [77]:
m.T

matrix([[5, 3],
        [2, 4]])

In [78]:
m.I

matrix([[ 0.28571429, -0.14285714],
        [-0.21428571,  0.35714286]])

In [79]:
m.dtype

dtype('int32')

In [80]:
m.nbytes

16

In [81]:
m.ndim

2

In [82]:
m.size

4

In [83]:
m.real

matrix([[5, 2],
        [3, 4]])

In [84]:
m

matrix([[5, 2],
        [3, 4]])

In [86]:
m.imag

matrix([[0, 0],
        [0, 0]])

m.shape

In [87]:
m.shape

(2, 2)

In [88]:
m.strides

(8, 4)

In [89]:
m.H

matrix([[5, 3],
        [2, 4]])

In [90]:
arr_a = np.mat(data="1,2;3,4")


In [91]:
arr_a

matrix([[1, 2],
        [3, 4]])

In [92]:
arr_b = np.asmatrix(data="1,2;3,4")

In [93]:
arr_b

matrix([[1, 2],
        [3, 4]])

In [94]:
arr_a[0,1]

2

In [97]:
a = np.array([[1, 2, 3],[7,8,9]])
b = np.array([[4,5,3],[1,2,3]])

In [98]:
np.c_[a,b]

array([[1, 2, 3, 4, 5, 3],
       [7, 8, 9, 1, 2, 3]])

In [99]:
n1 = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [100]:
 n1.reshape(2, 4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [101]:
n1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [102]:
n1.shape

(8,)

In [103]:
n1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [107]:
n2 = n1.reshape(2,4)

n2

In [108]:
n2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [111]:
n2.shape

(2, 4)

In [112]:
n2.shape = 8

In [113]:
n2

array([1, 2, 3, 4, 5, 6, 7, 8])

In [145]:
n3 = n1.reshape(2, 2, -1) 

In [146]:
n3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [147]:
n3.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [148]:
n3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [149]:
n3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [150]:
n3.T

array([[[1, 5],
        [3, 7]],

       [[2, 6],
        [4, 8]]])

n4

In [142]:
n3.resize(2,4)

In [143]:
n3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [131]:
n3.shape = 8

NameError: name 'array' is not defined

### n5

In [157]:
n = np.arange(18).reshape(2,3,3)

In [158]:
n

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [159]:
n.shape

(2, 3, 3)

In [162]:
n = n.ravel()

In [163]:
n.shape

(18,)

In [164]:
dt = np.dtype([('age',np.float32)]) 

In [165]:
dt

dtype([('age', '<f4')])

In [166]:
a = np.array([(10,),(20,),(30,)], dtype = dt)

In [167]:
a

array([(10.,), (20.,), (30.,)], dtype=[('age', '<f4')])

In [169]:
a["age"][1]

20.0

In [170]:
n = np.array(['1', '2', '0', '4'])

In [171]:
n

array(['1', '2', '0', '4'], dtype='<U1')

In [172]:
n2 = n.astype(float)

In [173]:
n2

array([1., 2., 0., 4.])

In [174]:
a = np.mat(data="1,2;3,4")

In [175]:
a

matrix([[1, 2],
        [3, 4]])

In [176]:
b = np.asmatrix([[5,6],[7,8]])

In [177]:
b

matrix([[5, 6],
        [7, 8]])

In [180]:
a = np.mat([1,2,3,4,5])

In [181]:
a


matrix([[1, 2, 3, 4, 5]])

In [182]:
arr_a = np.array([[1, 2], [3, 4]])
arr_b = np.array([[5, 6], [7, 8]])

In [183]:
np.dot(arr_a,arr_b)

array([[19, 22],
       [43, 50]])

In [184]:
np.multiply(arr_a,arr_b)

array([[ 5, 12],
       [21, 32]])

In [185]:
arr_a*arr_b

array([[ 5, 12],
       [21, 32]])

In [186]:
a = np.mat([[1, 2], [3, 4]])
b = np.mat([[5, 6], [7, 8]])

In [187]:
np.dot(a,b)

matrix([[19, 22],
        [43, 50]])

In [189]:
a*b

matrix([[19, 22],
        [43, 50]])

In [190]:
np.multiply(a,b)

matrix([[ 5, 12],
        [21, 32]])

In [209]:
x = np.array([[1, 2], [3, 4]])

In [210]:
x

array([[1, 2],
       [3, 4]])

In [211]:
x[0][1]=15

In [194]:
m

matrix([[1, 2],
        [3, 4]])

In [212]:
x

array([[ 1, 15],
       [ 3,  4]])

In [214]:
y = np.mat("1,2;3,4")

In [215]:
y

matrix([[1, 2],
        [3, 4]])

In [217]:
y[0,1] = 17

In [218]:
y

matrix([[ 1, 17],
        [ 3,  4]])

In [227]:
x

array([[1, 2],
       [3, 4]])

In [228]:
x = np.array([[1, 2], [3, 4]])

In [229]:
m = np.asmatrix(x)

In [230]:
m

matrix([[1, 2],
        [3, 4]])

In [231]:
y = np.array(m)

In [232]:
y

array([[1, 2],
       [3, 4]])

In [233]:
y = np.mat("1,2;a,4")

ValueError: malformed node or string: <ast.Name object at 0x0000018F457CAEB0>

In [237]:
np.array(['t','g'])

array(['t', 'g'], dtype='<U1')

In [238]:
np.mat(['t','g'])

matrix([['t', 'g']], dtype='<U1')

In [243]:
a = np.mat([1])

In [244]:
a

matrix([[1]])

In [245]:
a.ndim

2

In [246]:
a[0,0]

1

In [247]:
a[0,1]

IndexError: index 1 is out of bounds for axis 1 with size 1

In [261]:
x= np.array([1,2,3,4,5])

In [262]:
x

array([1, 2, 3, 4, 5])

In [250]:
x.ndim

1

In [263]:
y = np.mat(x)

In [264]:
y

matrix([[1, 2, 3, 4, 5]])

In [253]:
y.ndim

2

In [257]:
y

matrix([[1, 2, 3, 4, 5]])

In [258]:
b = np.array(y)

In [270]:
b

array([[1, 2, 3, 4, 5]])

In [271]:
b.ndim

2

In [275]:
b[0]

array([1, 2, 3, 4, 5])

In [269]:
x

array([1, 2, 3, 4, 5])

In [276]:
m = np.mat([1,2,3])

In [277]:
m

matrix([[1, 2, 3]])

In [278]:
m[0]

matrix([[1, 2, 3]])

In [279]:
a


matrix([[1]])

In [280]:
x

array([1, 2, 3, 4, 5])

In [281]:
x.T

array([1, 2, 3, 4, 5])

In [287]:
x = np.array([[1, 2], [3, 4],[5,6]])

In [288]:
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [289]:
x.T

array([[1, 3, 5],
       [2, 4, 6]])

In [290]:
np.transpose(x)

array([[1, 3, 5],
       [2, 4, 6]])

In [291]:
x.I


AttributeError: 'numpy.ndarray' object has no attribute 'I'

In [294]:
x = np.mat([[1,2],[3,4]])

In [297]:
x

matrix([[1, 2],
        [3, 4]])

In [296]:
x.I

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

In [298]:
A = np.array( [[1,2],
               [3,4]] )
B = np.array( [[5,6],
               [7,8]] )

In [299]:
np.matmul(A,B)

array([[19, 22],
       [43, 50]])

In [300]:
A*B

array([[ 5, 12],
       [21, 32]])

In [301]:
A = np.mat( [[1,2],
               [3,4]] )
B = np.mat( [[5,6],
               [7,8]] )

In [302]:
A*B

matrix([[19, 22],
        [43, 50]])

In [303]:
np.matmul(A,B)

matrix([[19, 22],
        [43, 50]])

In [304]:
A.dot(B)

matrix([[19, 22],
        [43, 50]])

In [305]:
B.dot(A)

matrix([[23, 34],
        [31, 46]])